### ISSUE TITLE
truffle.js: "develop" should be "development"

### ISSUE THREAD

**Issue by english4coder** [Blockchain-book/Ethereum-Score-Hella#1]
develop需要改为development才可部署成功

**Comment by sunlggggg** [comment]
@pacobai 你好，我这边是可以使用develop的，可能不同版本的原因。
![image](https://user-images.githubusercontent.com/20771250/44852325-8d911400-ac95-11e8-9bdd-a68262647599.png)
这是我的truffle版本，你可以对比一下。
![image](https://user-images.githubusercontent.com/20771250/44852390-b3b6b400-ac95-11e8-9362-f97b2de27379.png)
